name: ci
on: [workflow_dispatch]

jobs:
  test:
    runs-on: shipping
    env:
      GROUP: weaveworksdemos
      COMMIT: ${{ github.sha }}
      REPO: shipping
      DOCKER_REGISTRY: 172.16.238.184
      APP_NAME: docker-local
      JFROG_USER_WRITER: ${{ secrets.JFROG_USER_WRITER }}
      JFROG_PASSWORD_WRITER: ${{ secrets.JFROG_PASSWORD_WRITER }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B -DskipTests package --file pom.xml

      - name: Unit Tests
        run: mvn -q test

      - name: Integration Tests
        run: mvn integration-test
      
                    
      # Login & Build & Push to artifactory 
      - name: Login to JFrog
        uses: actions/checkout@v3
        with:
          registry: https://172.16.238.184
          username: ${{ secrets.JFROG_USER_WRITER }}
          password: ${{ secrets.JFROG_PASSWORD_WRITER }}
      
      

      - name: Build the Docker image
        run: docker build . --tag "$DOCKER_REGISTRY/$APP_NAME:1.0.${{ github.run_id }}"

      - name: Push to JFrog
        run: docker push "$DOCKER_REGISTRY/$APP_NAME:1.0.${{ github.run_id }}"
